version: "3"
services:
  db:
    image: postgres:14-alpine
    expose:
      - 5432
    volumes:
      - /home/fredrik/.pdfreader-docker/postgres:/var/lib/postgresql/data
      - /etc/passwd:/etc/passwd:ro
    user: 1000:1000
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pdfreader
      PGDATA: /var/lib/postgresql/data/pgdata
  pdfreader:
    image: pdfreader:test
    ports:
      - 80:8000
    volumes:
      - /home/fredrik/.pdfreader-docker:/pdf_reader
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    environment:
      PDF_READER_DATABASE_LOCATION: postgres://postgres:password@db:5432
      USER: 1000
