import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { Documents } from "../components/documents";
import { Uploader } from "../components/uploader";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Wrapper />
      </main>
    </div>
  );
};

function Wrapper() {
  const [currentDocument, setDocument] = useState<string | null>(null);

  let text: string;
  if (currentDocument === null) {
    text = "No document selected";
  } else {
    text = `Current document is ${currentDocument}`;
  }

  const updateDocument = (doc: string) => {
    console.log(doc);
    setDocument(doc);
  };
  return (
    <>
      <Uploader />
      <Documents updateDocument={updateDocument} />
      <p>{text}</p>
    </>
  );
}

export default Home;
